### ISSUE TITLE
Regarding the training dataset size while fitting a svm classifier

### ISSUE THREAD

**Issue by fugokidi** [pralab/secml#3]
While fitting `CClassifierSVM`, it automatically used 3 fold dataset split.
Is it possible to fit the model to the whole training dataset?
Is there any parameter that I can change to control the size of the training dataset?

**Comment by m-melis** [comment]
Hi @fugokidi, thanks for raising this issue.

The `CClassifierSVM.fit(x, y)` method should fit the model on the whole dataset. Instead, while using the `CClassifierSVM.estimate_parameters()` method to find the best parameters you can customize the number of folds in the `num_folds` parameter of the `CDataSplitter` you are passing.

There is also an additional method of `CClassifierSVM`, called `fit_forward` which currently uses a `CDataSplitterKFold` with a fixed number of folds equal to 5 and cannot be changed.

This should be the expected behavior. If you find anything different please let us know.

**Comment by fugokidi** [comment]
Hi @m-melis, thank you for your quick reply. I'm clear now. Today is the first day of using this library. I shall definitely report i find anything different. Thank you again.
